services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: divaldoh
      MYSQL_PASSWORD: 123456
      MYSQLD_OPTS: "--default-authentication-plugin=mysql_native_password"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/

volumes:
  mysql_data:
